### PR TITLE
Require async-2.0, otherwise Control.Concurrent.Async is not available

### PR DESCRIPTION
**Pull request by Bodigrim**

### CODE REVIEW

**Comment by tomjaguarpaw** [comment]
This indeed appears to be so. The module is called `Control.Async` in the `1.x` series! But how did you come across this issue? The last in the `1.x` series was released 11 years ago so I'm surprised you could find a practical
install plan that includes it.

@snoyberg For Hackage/Cabal this doesn't actually require a release: I can adjust the bounds with a revision. I don't know about Stack/Stackage: what should we do for them? (I guess they don't require any change since all versions are pinned.)

**Comment by snoyberg** [comment]
@tomjaguarpaw nothing needed on the Stack/Stackage front.

**Comment by tomjaguarpaw** [comment]
OK, I'll merge this presently and do a Hackage revision.

**Comment by Bodigrim** [comment]
> But how did you come across this issue?

I've been testing GHC 9.4-alpha1, for which `async-1.4` satisfies constraints out of the box, but `async-2.0` does not.

**Comment by Bodigrim** [comment]
@tomjaguarpaw just a gentle ping.

**Comment by tomjaguarpaw** [comment]
@Bodigrim Thank you for the ping.

Interestingly, many of the old versions of `typed-process` already had a revision of the lower bound to `aeson >= 2.0.1`, so I applied that to the newer ones. (They also had an upper bound but I didn't apply that to the newer ones.)  Let's revisit the issue of upper bound if its absence becomes a problem.

**Pull request merged**
